// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package aptostypes

import (
	"encoding/json"
	"errors"
	"math/big"
)

var _ = (*ledgerInfoMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (l LedgerInfo) MarshalJSON() ([]byte, error) {
	type LedgerInfo struct {
		ChainId         int    `json:"chain_id"`
		LedgerVersion   *Big   `json:"ledger_version" gencodec:"required"`
		LedgerTimestamp *Big   `json:"ledger_timestamp" gencodec:"required"`
		Epoch           int    `json:"epoch"`
		NodeRole        string `json:"node_role"`
	}
	var enc LedgerInfo
	enc.ChainId = l.ChainId
	enc.LedgerVersion = (*Big)(l.LedgerVersion)
	enc.LedgerTimestamp = (*Big)(l.LedgerTimestamp)
	enc.Epoch = l.Epoch
	enc.NodeRole = l.NodeRole
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (l *LedgerInfo) UnmarshalJSON(input []byte) error {
	type LedgerInfo struct {
		ChainId         *int    `json:"chain_id"`
		LedgerVersion   *Big    `json:"ledger_version" gencodec:"required"`
		LedgerTimestamp *Big    `json:"ledger_timestamp" gencodec:"required"`
		Epoch           *int    `json:"epoch"`
		NodeRole        *string `json:"node_role"`
	}
	var dec LedgerInfo
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ChainId != nil {
		l.ChainId = *dec.ChainId
	}
	if dec.LedgerVersion == nil {
		return errors.New("missing required field 'ledger_version' for LedgerInfo")
	}
	l.LedgerVersion = (*big.Int)(dec.LedgerVersion)
	if dec.LedgerTimestamp == nil {
		return errors.New("missing required field 'ledger_timestamp' for LedgerInfo")
	}
	l.LedgerTimestamp = (*big.Int)(dec.LedgerTimestamp)
	if dec.Epoch != nil {
		l.Epoch = *dec.Epoch
	}
	if dec.NodeRole != nil {
		l.NodeRole = *dec.NodeRole
	}
	return nil
}
